# PyInstaller hook for Playwright
# This ensures all Playwright modules are included in the executable

from PyInstaller.utils.hooks import collect_all

# Collect all Playwright modules
datas, binaries, hiddenimports = collect_all("playwright")

# Additional Playwright-specific hidden imports
hiddenimports += [
    "playwright.async_api",
    "playwright.sync_api",
    "playwright._impl._browser_context",
    "playwright._impl._browser",
    "playwright._impl._page",
    "playwright._impl._connection",
    "playwright._impl._transport",
    "playwright._impl._driver",
    "playwright._impl._browser_type",
    "playwright._impl._playwright",
    "playwright._impl._api_types",
    "playwright._impl._api_structures",
    "playwright._impl._errors",
    "playwright._impl._object_factory",
    "playwright._impl._network",
    "playwright._impl._cdp_session",
    "playwright._impl._frame",
    "playwright._impl._element_handle",
    "playwright._impl._js_handle",
    "playwright._impl._worker",
    "playwright._impl._route",
    "playwright._impl._request",
    "playwright._impl._response",
    "playwright._impl._websocket",
    "playwright._impl._video",
    "playwright._impl._tracing",
    "playwright._impl._accessibility",
    "playwright._impl._locator",
    "playwright._impl._expect",
    "playwright._impl._selector_parser",
    "playwright._impl._string_utils",
    "playwright._impl._timeout_settings",
    "playwright._impl._waiter",
    "playwright._impl._event_context_manager",
    "playwright._impl._api_structures",
    "playwright._impl._api_types",
    "playwright._impl._browser_context",
    "playwright._impl._browser",
    "playwright._impl._page",
    "playwright._impl._connection",
    "playwright._impl._transport",
    "playwright._impl._driver",
    "playwright._impl._browser_type",
    "playwright._impl._playwright",
    "playwright._impl._errors",
    "playwright._impl._object_factory",
    "playwright._impl._network",
    "playwright._impl._cdp_session",
    "playwright._impl._frame",
    "playwright._impl._element_handle",
    "playwright._impl._js_handle",
    "playwright._impl._worker",
    "playwright._impl._route",
    "playwright._impl._request",
    "playwright._impl._response",
    "playwright._impl._websocket",
    "playwright._impl._video",
    "playwright._impl._tracing",
    "playwright._impl._accessibility",
    "playwright._impl._locator",
    "playwright._impl._expect",
]
