name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev
        uv sync --group build

    - name: Install Playwright browsers
      run: |
        uv run python -m playwright install chromium

    - name: Build executable using build script (debug mode)
      run: |
        uv run python build_executable.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: EmailToPDFConverter-Windows
        path: dist/EmailToPDFConverter.exe