name: Quick Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Install Playwright browsers
      run: |
        uv run python -m playwright install chromium

    - name: Run tests
      run: |
        uv run pytest tests/ -v --tb=short

    - name: Run linting
      run: |
        uv run ruff check tests/ eml_to_pdf_converter.py